# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Zerina-MovieMoment' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Zerina-MovieMoment
pod 'SDWebImage', '~> 4.0'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Alamofire', '~> 4.5'
pod 'SwiftyJSON'
pod 'IQKeyboardManagerSwift', '>= 5.0.0'
pod 'ProjectOxfordFace'
pod 'youtube-ios-player-helper', :git=>'https://github.com/youtube/youtube-ios-player-helper', :commit=>'head'
end
